# Generated by Django 3.0.6 on 2020-05-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('numero_control', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=35)),
                ('apellido_materno', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('curp', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
    ]
